name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  Now it is:
    runs-on: ubuntu-20.04
    steps:
      - name: print date
        run: |
          date

  Dictory content:
    runs-on: ubuntu-20.04
    steps:
      - name: print files
        run: |
          ls -l